BlogCore/Areas/Admin/Controllers/ArticlesController.cs
using BlogCore.Data;
using BlogCore.DataAccess.Data.Repository;
using BlogCore.DataAccess.Data.Repository.IRepository;
using BlogCore.Models;
using BlogCore.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Data;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace BlogCore.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]

    [Area("Admin")]
    public class ArticlesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public ArticlesController(IUnitOfWork unitOfWork, IWebHostEnvironment hostingEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            ArticlesVM artvm = new ArticlesVM()
            {
                Article = new BlogCore.Models.Article(),
                CategoryList = _unitOfWork.Category.GetListAllCategories()
            };

            return View(artvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ArticlesVM model)
        {
            if (ModelState.IsValid)
            {
                string pathPrincipal = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (model.Article.Id == 0)
                {
                    string nameFile = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(pathPrincipal, @"images\articles");
                    var extention = Path.GetExtension(files[0].FileName);

                    using (var fileStreams = new FileStream(Path.Combine(uploads, nameFile + extention), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }
                    model.Article.UrlImage = @"\images\articles\" + nameFile + extention;
                    model.Article.DateCreate = DateTime.Now.ToString();

                    _unitOfWork.Articles.Add(model.Article);
                    _unitOfWork.Save();

                    return RedirectToAction("Index");
                }
            }

            model.CategoryList = _unitOfWork.Category.GetListAllCategories();
            return View(model);

        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ArticlesVM artvm = new ArticlesVM()
            {
                Article = new BlogCore.Models.Article(),
                CategoryList = _unitOfWork.Category.GetListAllCategories()
            };

            if (id != null)
            {
                artvm.Article = _unitOfWork.Articles.Get(id.GetValueOrDefault());
            }

            return View(artvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ArticlesVM model)
        {
            if (ModelState.IsValid)
            {
                string pathPrincipal = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                var articleFromDB = _unitOfWork.Articles.Get(model.Article.Id);



                if (files.Count() > 0)
                {
                    string nameFile = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(pathPrincipal, @"images\articles");
                    var extention = Path.GetExtension(files[0].FileName);
                    var NewExtension = Path.GetExtension(files[0].FileName);

                    var pathImagen = Path.Combine(pathPrincipal, articleFromDB.UrlImage.TrimStart('\\'));

                    if (System.IO.File.Exists(pathImagen))
                    {
                        System.IO.File.Delete(pathImagen);
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, nameFile + extention), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }

                    model.Article.UrlImage = @"\images\articles\" + nameFile + extention;
                    model.Article.DateCreate = DateTime.Now.ToString();

                    _unitOfWork.Articles.Update(model.Article);
                    _unitOfWork.Save();

                    return RedirectToAction("Index");
                }
                else
                {
                    model.Article.UrlImage = articleFromDB.UrlImage;


                }

                _unitOfWork.Articles.Update(model.Article);
                _unitOfWork.Save();
                return RedirectToAction("Index");

            }

            model.CategoryList = _unitOfWork.Category.GetListAllCategories();
            return View(model);

        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {

            var articleFromDB = _unitOfWork.Articles.Get(id);
            string pathPrincipal = _hostingEnvironment.WebRootPath;
            var pathImagen = Path.Combine(pathPrincipal, articleFromDB.UrlImage.TrimStart('\\'));

            if (System.IO.File.Exists(pathImagen))
            {
                System.IO.File.Delete(pathImagen);
            }

            var objFromDb = _unitOfWork.Articles.Get(id);

            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error borrando articulo" });
            }

        

            _unitOfWork.Articles.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "articulo borrada correctamente" });

        }


        #region API Call

        [HttpGet]
        public IActionResult GetAll()
        {
            //Opcion 1
            return Json(new { data = _unitOfWork.Articles.GetAll(includeProperties: "Categories") });
        }


    }
    #endregion
}

BlogCore/Areas/Admin/Controllers/SlidersController.cs
using BlogCore.Data;
using BlogCore.DataAccess.Data.Repository;
using BlogCore.DataAccess.Data.Repository.IRepository;
using BlogCore.Models;
using BlogCore.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Data;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace BlogCore.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]

    [Area("Admin")]
    public class SlidersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public SlidersController(IUnitOfWork unitOfWork, IWebHostEnvironment hostingEnvironment)
        {
            _unitOfWork = unitOfWork;
            _hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {         

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Slider model)
        {
            if (ModelState.IsValid)
            {
                string pathPrincipal = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
               
                    string nameFile = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(pathPrincipal, @"images\sliders");
                    var extention = Path.GetExtension(files[0].FileName);

                    using (var fileStreams = new FileStream(Path.Combine(uploads, nameFile + extention), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }
                model.UrlImage = @"\images\sliders\" + nameFile + extention;

                    _unitOfWork.Sliders.Add(model);
                    _unitOfWork.Save();

                    return RedirectToAction("Index");
                
            }

            return View(model);

        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
           
            if (id != null)
            {
                var slider = _unitOfWork.Sliders.Get(id.GetValueOrDefault());
                return View(slider);

            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Slider model)
        {
            if (ModelState.IsValid)
            {
                string pathPrincipal = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                var sliderFromDB = _unitOfWork.Sliders.Get(model.Id);



                if (files.Count() > 0)
                {
                    string nameFile = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(pathPrincipal, @"images\sliders");
                    var extention = Path.GetExtension(files[0].FileName);
                    var NewExtension = Path.GetExtension(files[0].FileName);

                    var pathImagen = Path.Combine(pathPrincipal, sliderFromDB.UrlImage.TrimStart('\\'));

                    if (System.IO.File.Exists(pathImagen))
                    {
                        System.IO.File.Delete(pathImagen);
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, nameFile + extention), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }

                    model.UrlImage = @"\images\sliders\" + nameFile + extention;

                    _unitOfWork.Sliders.Update(model);
                    _unitOfWork.Save();

                    return RedirectToAction("Index");
                }
                else
                {
                    model.UrlImage = sliderFromDB.UrlImage;


                }

                _unitOfWork.Sliders.Update(model);
                _unitOfWork.Save();
                return RedirectToAction("Index");

            }

            return View();

        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {

            var sliderFromDB = _unitOfWork.Sliders.Get(id);
      

        

            if (sliderFromDB == null)
            {
                return Json(new { success = false, message = "Error borrando slider" });
            }

        

            _unitOfWork.Sliders.Remove(sliderFromDB);
            _unitOfWork.Save();
            return Json(new { success = true, message = "slider borrado correctamente" });

        }


        #region API Call

        [HttpGet]
        public IActionResult GetAll()
        {
            //Opcion 1
            return Json(new { data = _unitOfWork.Sliders.GetAll() });
        }


    }
    #endregion
}

BlogCore/Areas/Admin/Controllers/UsersController.cs
using BlogCore.DataAccess.Data.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;

namespace BlogCore.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]

    [Area("Admin")]
    public class UsersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public UsersController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [HttpGet]
        public IActionResult Index()
        {//
           // return View(_unitOfWork.Users.GetAll());

            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var CurrentUser = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return View(_unitOfWork.Users.GetAll(u=> u.Id != CurrentUser.Value));

        }

        [HttpGet]
        public IActionResult Block(string id)
        {
            if (id == null)
            {
                return NotFound();

            }
            _unitOfWork.Users.BlockUser(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult UnBlock(string id)
        {
            if (id == null)
            {
                return NotFound();

            }
            _unitOfWork.Users.UnBlockUser(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

BlogCore/Views/Shared/_Layout.cshtml
@using BlogCore.Utilities;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogCore.styles.css" asp-append-version="true" />

    <!--Plugins-->

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <!--Plugins-->

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Client" asp-controller="Home" asp-action="Index">Blog Core 7</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">

                        @if (User.IsInRole(CNT.Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><spam class="text-white">Contenidos</spam></a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Categories" asp-action="Index">Categorías</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Articles" asp-action="Index">Articúlos</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Sliders" asp-action="Index">Slider</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Index">Usuarios</a>

                                </div>
                            </li>
                            
                        }

                    </ul>

                </div>
                <partial name="_LoginPartial" />

            </div>
        </nav>
        @if (ViewBag.IsHome == true)
        {
            <partial name="_Slider" />
        }


    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BlogCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!--Plugins-->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/0f48d8c00d.js" crossorigin="anonymous"></script>
    <!--Plugins-->


    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogCore/Views/Shared/_Slider.cshtml
@model BlogCore.Models.ViewModels.HomeVM


<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">

        @{
            int count = 0;

            @foreach (var item in Model.Slider.Where(s => s.State == true))
            {
                var itemDinamic = count++ == 0 ? "item active" : "item";


                <div class="carousel-item @itemDinamic">
                    <img src="@Url.Content(item.UrlImage)" class="d-block w-100 h-50">
                    <h2 class="text-white text-center bg-dark py-1">@Html.Raw(item.Name)</h2>
                </div>

            }
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

BlogCore/Views/Shared/_ViewCreateBack.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control"> Create</button>
    </div>
    &nbsp;
    <div class="col">
        <a asp-action="Index" class=" btn btn-success form-control">Volver a Lista</a>
    </div>
</div>